@extends('layouts.app')

@section('page_title', 'Verify Report')

@push('styles')
    <link href="{{ asset('css/reports.css') }}" rel="stylesheet" />
@endpush

@section('content')
<div class="reports-shell">
    <section class="reports-hero verify-hero">
        <div class="reports-hero-copy">
            <div class="report-brand-row">
                <img src="{{ asset('images/vilocarelogo.png') }}" alt="ViLoCare Logo" class="report-hero-logo" />
                <div>
                    <span class="reports-kicker">Report authentication</span>
                    <h2>Verify a ViLoCare Report</h2>
                </div>
            </div>
            <p>Scan or enter the report reference from a generated barcode to confirm the report originated from ViLoCare and review its summary details.</p>
        </div>
    </section>

    <section class="report-filter-panel">
        <form method="GET" action="{{ route('reports.verify') }}" class="verify-form">
            <div class="filter-field filter-field-grow">
                <label for="reference">Report Reference</label>
                <input id="reference" name="reference" value="{{ $reference }}" class="form-control" placeholder="Scan or enter report reference">
            </div>
            <div class="filter-actions">
                <button type="submit" class="btn btn-primary">Verify</button>
                <a href="{{ route('reports.index') }}" class="btn btn-outline-secondary">Back to reports</a>
            </div>
        </form>
    </section>

    @if($reference !== '' && ! $report)
        <section class="report-panel">
            <div class="empty-verify-state">
                <h3>Report not found</h3>
                <p>No stored ViLoCare report matched reference <strong>{{ $reference }}</strong>. Check the code and try again.</p>
            </div>
        </section>
    @endif

    @if($report)
        <section class="exports-board">
            <article class="export-card">
                <div>
                    <h3>{{ $report['title'] }}</h3>
                    <p>Authenticated report generated by ViLoCare.</p>
                </div>
                <div class="verify-badge">Verified</div>
            </article>
            <article class="export-card">
                <div>
                    <h3>Reference</h3>
                    <p>{{ $report['reference'] }}</p>
                </div>
                <div>
                    <h3>Generated</h3>
                    <p>{{ $report['generated_at_human'] }}</p>
                </div>
            </article>
            <article class="export-card barcode-card">
                <div class="barcode-wrap">
                    {!! $report['barcode_svg'] !!}
                </div>
            </article>
        </section>

        <section class="reports-summary-grid">
            @foreach($report['summary_cards'] as $card)
                <article class="report-summary-card">
                    <span class="summary-badge">{{ strtoupper(substr($card['label'], 0, 2)) }}</span>
                    <div>
                        <p>{{ $card['label'] }}</p>
                        <strong>{{ $card['value'] }}</strong>
                    </div>
                </article>
            @endforeach
        </section>

        <section class="report-panel">
            <div class="panel-head">
                <div>
                    <h3>Report Summary</h3>
                    <p>Verified metadata for this generated report.</p>
                </div>
            </div>
            <div class="verification-grid">
                <div class="verification-block">
                    <h4>Applied Filters</h4>
                    <dl class="verification-list">
                        @foreach($report['filters'] as $label => $value)
                            <div>
                                <dt>{{ $label }}</dt>
                                <dd>{{ $value }}</dd>
                            </div>
                        @endforeach
                    </dl>
                </div>

                <div class="verification-block">
                    <h4>Source</h4>
                    <dl class="verification-list">
                        <div>
                            <dt>Website</dt>
                            <dd>{{ $report['website'] }}</dd>
                        </div>
                        <div>
                            <dt>Footer Summary</dt>
                            <dd>{{ $report['footer_text'] }}</dd>
                        </div>
                    </dl>
                </div>
            </div>
        </section>
    @endif
</div>
@endsection
